[package]
name = "chess_derives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
chess-lib = {path = "../chess_lib"}
syn = "1.0.107"
